### PR TITLE
Fix optional params

### PR DESCRIPTION
**Pull request by vitaliystoliarovcc**
### Description

Fix auth requests with nullish parameters

### Fixes:
- [x] Omit nullish parameters of request

### PR status:
- [x]  Version bumped
- [x]  Change-log updated
- [x]  Tests added or updated
- [x] Documentation updated

### CODE REVIEW

**Review by avsek477 — APPROVED** [review]
lgtm

**Review by tarcisiozf — APPROVED** [review]

**Review by vigan-abd — CHANGES_REQUESTED** [review]
Changes look good, could you add also a test case for this one please? maybe we can use sinon to spy or something, not sure how
Also please follow the PR template e.g. like this https://github.com/bitfinexcom/bfx-api-node-rest/pull/85, in your case **Description** and **PR status** sections are missing
And could you prepare package bump (should be patch), changelog updates, and update generated docs?

**Comment by vitaliystoliarovcc** [comment]
@vigan-abd done

**Review by vigan-abd — APPROVED** [review]
lgtm

**Pull request merged**
